# Generated by Django 4.2.4 on 2023-09-01 12:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_yazi_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yazi',
            options={'verbose_name_plural': 'Yazilar'},
        ),
        migrations.AlterField(
            model_name='yazi',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='baslik', unique=True),
        ),
    ]
