# Generated by Django 4.2.4 on 2023-09-04 12:27

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_yazi_options_alter_yazi_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True)),
                ('textbody1', models.TextField(blank=True, null=True)),
                ('photo1', models.URLField(blank=True, null=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('textbody2', models.TextField(blank=True, null=True)),
                ('photo2', models.URLField(blank=True, null=True)),
                ('textbody3', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
    ]
