# Generated by Django 4.2.4 on 2023-09-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
